export enum CampaignConst {
    CAMPAIGNNAME="CAMPAIGNNAME",
    BUDGET="BUDGET",
    STARTDATE= "STARTDATE",
    ENDDATE="ENDDATE",
    DAYOFWEEK="DAYOFWEEK",
    DAYPARTS="DAYPARTS",
    PLATFORM="PLATFORM",
    ADVERTISER="ADVERTISER",
    CREATIVEFORMAT="CREATIVEFORMAT"
    
}

export default CampaignConst;