/* eslint-disable */ 
export const NavBarConstants = {
    HOME:"HOME",
    DASHBOARD:"DASHBOARD",
    AUDIENCELIST:"AUDIENCE",
    AUDIENCESIZING:"AUDIENCESIZING",
    LOGINTOGGLE:"LOGINLOGOUT",
    TERMINOLOGY:"TERMINOLOGY",
    FEEDBACK:"FEEDBACK",
    ADMIN:"ADMIN",
    ADMINAUDIENCESEGMENT:"ADMINAUDIENCESEGMENT",
    AUDIENCETRAIT:"AUDIENCETRAIT",
    REPORTINGLIST:"REPORTING",
    CRMUPLOADER:"CRMUPLOADER",
    REQUESTS:"REQUESTS",
    TV:"TV",
    DIGITAL:"Reporting",
    
    

    HOMESLICK : 0,
    DASHBOARDSLICK : 1,
    AUDIENCELISTSLICK : 2,
    
    AUDIENCESIZINGSLICK : 3,
    PLANNINGSLICK : 4,
    CAMPAIGNSLICK : 5,
    EMAILCONFPAGESLICK : 6,
    INSIGHTSLICK : 7,
    TERMINOLOGYSLICK:8,
    FEEDBACKSLICK:9,
    ADMINSLICK:10,
    ADMINADDUSER:11,
    AUDIENCETRAITSLICK:12,
    REPORTINGLISTSLICK:13,
    CRMSLICK : 14,
    REQUESTSLISTSLICK:15,
    SUBMENU:9997,
    NONMENU:9998,
    ALL:9999

}

export default NavBarConstants;